package com.adMaroc.Tecdoc.BackOffice.Repository;

import  com.adMaroc.Tecdoc.BackOffice.Models.TecdocData.TheAllocationOfQuickStartIconsToNodesLeavesWithinOneProductArea;
import  com.adMaroc.Tecdoc.BackOffice.Models.TecdocData.compositeKeys.TheAllocationOfQuickStartIconsToNodesLeavesWithinOneProductAreaId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface TheAllocationOfQuickStartIconsToNodesLeavesWithinOneProductAreaRepository extends JpaRepository<TheAllocationOfQuickStartIconsToNodesLeavesWithinOneProductArea, TheAllocationOfQuickStartIconsToNodesLeavesWithinOneProductAreaId> {


}
